### ISSUE TITLE
[Feature request] Support for Github Enterprise

### ISSUE THREAD

**Issue by matthizou** [N1ck/gifs-for-github#12]
Lot's of companies are using Github enterprise on locally hosted domains. 
For instance, we also have the same fun "convention" in mine, to add a gif to our PRs, and I am sure this extension would take off if it had an option to configure the domain. 

Github Dark theme extension does it great, a simplified similar interface could be used:
![image](https://user-images.githubusercontent.com/6507291/84578591-fa23c700-adc6-11ea-9f29-86812712d615.png)

I could be interested to contribute for that if you are interested, keep in touch. Cheers

**Comment by N1ck** [comment]
Hey @matthizou 👋 That's a great suggestion. 

Another option would be to use the module used by refined-github: https://github.com/fregante/webext-domain-permission-toggle. This should be pretty easy to add too! 

If you are interested in contributing I think this would be a great addition. Let me know if you want to have a go at it, otherwise I am happy to take a look in the next week or so 🙂

**Comment by matthizou** [comment]
Hey! Thanks for the reply 
👍  Either way would be great. They each have pros and cons: 
* `webpext-domain-permission-toggle` comes pre-canned and makes implementing this suggestion a really quick win. I am not a big fan of having to right-click on the icon and find this entry, it is not intuitive if you don't read the docs.
* Custom implementation (like the one above) is more work. Ultimately, it is better for the user (imo), as they can do left-click on the icon and understand the interface intuitively. No need to browse the readme to find how to do it.

Last month I went for a custom implementation (https://github.com/matthizou/github-show-avatars/blob/master/extension/images/screenshots/popup-1.png), which work great, but am thinking of switching to something like the one from the Dark theme posted above, that I find even clearer.

I would suggest we start simple (`webpext-domain-permission-toggle`), I'll let you do it if it is ok with you. Ping me if you are interested later on to do something more custom.

**Comment by N1ck** [comment]
@matthizou sorry I took so long but I have pushed an update including  `webpext-domain-permission-toggle`. If you want to take a crack at a custom UI version at some point you are more than welcome 🙂 I agree that this implementation is not as discoverable.

**Comment by matthizou** [comment]
Glad to hear 👏 
No luck to make it work though, in my company's Github (it is activated + the browser has been reloaded)
![image](https://user-images.githubusercontent.com/6507291/89736027-ddbea680-da66-11ea-8f27-697e5a36280a.png)

I am not too surprised, as the 2 versions (enterprise and non-enterprise) have often major structural differences in the DOM - even in cases where they look the same. There are no errors in the console, though.
I will try to have a look a shot at it beginning of September except if work on it before. Keep it touch 👋

**Comment by N1ck** [comment]
I think it might be simply that I made a mistake with my most recent change 😅  with my release of the version to add the "Enable GIFs for GitHub" dropdown I failed to inject the content script on the custom domain.

![](https://media1.giphy.com/media/tZiLOffTNGoak/giphy.gif)

I have submitted another release `1.2.8` which I have verified will execute when the extension is enabled. I have still been unable to test GitHub enterprise, but I am crossing my fingers that the structure isn't different 🤞 

Hopefully this works for you, if not I would love it if you could take a look for me! Let me know if I can help at all.

**Comment by matthizou** [comment]
👍  I'll QA it when the new version will be released

**Comment by matthizou** [comment]
Working like a charm 👏
