### ISSUE TITLE
Popup window does not extend past the review / comment dropdown overlay

### ISSUE THREAD

**Issue by Gowiem** [N1ck/gifs-for-github#23]
Simple thing to deal with practically, but would be a nice fix to see at some point: If you open the GIF dropdown while in the "Files changed" section of a PR then it's cut off by the comment drowndown overlay. See screenshot below: 

![image](https://user-images.githubusercontent.com/1392040/99077699-61ae9000-257a-11eb-905e-427e9e8b9050.png)

**Comment by N1ck** [comment]
Thanks for submitting an issue for this @Gowiem . I found this really annoying too and had already made a fix for this, but after testing I totally forgot to release it. Sorry about that 😅 

![](https://media1.giphy.com/media/BsQAVgY6ksvIY/giphy.gif)

It should be resolved in the latest version (`2.8.11`) let me know!

**Comment by Gowiem** [comment]
Works great @N1ck -- Much appreciated! 

![image](https://user-images.githubusercontent.com/1392040/99198504-4304f080-2756-11eb-8fa0-90ffaceff9f3.png)

![](https://media4.giphy.com/media/ci0uDcGQtBh0k/giphy.gif)
