### ISSUE TITLE
Inquiry: <img> tag instead of markdown style

### ISSUE THREAD

**Issue by DATADEER** [N1ck/gifs-for-github#28]
Hey N1ck, thanks for providing this awesome plugin

<img src="https://media0.giphy.com/media/3o6ozm2sJ102JdumVq/giphy.gif" width="300px"/>

I wanted to ask if you'd be open for a PR that replaces the insertion of 

`![](https://media0.giphy.com/media/l4FGCdurj53YWZYYg/giphy.gif)`

with

`<img src="https://media0.giphy.com/media/l4FGCdurj53YWZYYg/giphy.gif"/>`

This way you can easily change the size of the gif with:

`<img src="https://media0.giphy.com/media/l4FGCdurj53YWZYYg/giphy.gif" width="100px"/>`

What do you think? 🙂

**Comment by N1ck** [comment]
Hey Lucca glad you like the extension! That should be a pretty simple change, I would definitely be open to a PR for this 👍

**Comment by e1himself** [comment]
I've came here to suggest adding `max-size` option to the extension, as I often find myself converting the markup to `<img>` to add `width` property to it, when I see that pasted GIF is taking too much space.

Anyway, thank you @N1ck for such an awesome extension :+1: :+1: :+1: 

![](https://media3.giphy.com/media/11x4WadFj5YdZS/giphy.gif)

**Comment by ritikbheda** [comment]
Hi @N1ck, I would like to work on this issue.
