### ISSUE TITLE
Stopped working on "Files changed" (review) tab

### ISSUE THREAD

**Issue by dgeelen-uipath** [N1ck/gifs-for-github#40]
Hi, first of all thanks for a great add on!

I'm not sure when, or if it's just me, but recently the "GIF" button has only been appearing on the "Conversation"-tab editor, and is no longer available on the code-review editor :(
It would be really nice if this functionality could be restored :)

**Comment by N1ck** [comment]
Thanks for raising this 🙌 

I have just merged a fix for the button not appearing when editing a comment in the "Conversation" tab (https://github.com/N1ck/gifs-for-github/pull/41). This should be out in the next release but let me know if it's still a problem.

I have taken a brief look at fixing it within the code-review editor and it's not quite as trivial. I will have a go at this when I have some time 💪

**Comment by timbrownsf** [comment]
Im still not seeing when I try to add a new comment on a line via the Files Changed tab

**Comment by trevor-atlas** [comment]
Still not seeing it 😢

**Comment by N1ck** [comment]
Sorry that it took so long to get to this. I am releasing a new version now that I hope resolves the issue

<img src="https://media3.giphy.com/media/l0ExbcOSoFGQMssF2/giphy.gif"/>
