### ISSUE TITLE
Add more GIF providers

### ISSUE THREAD

**Issue by LeonardsonCC** [N1ck/gifs-for-github#57]
I would like to get GIFs from other providers, like Tenor.
I actually made a fork and made it work, just would like to know if I should open a PR, or if it is out of scope for this project.

![image](https://user-images.githubusercontent.com/21212048/209038458-3bd685cf-eede-4dfa-8d88-42061ca0530f.png)

![image](https://user-images.githubusercontent.com/21212048/209038496-73df5c4c-c859-4b02-9bfc-672e021cb083.png)

**Comment by N1ck** [comment]
This is awesome @LeonardsonCC I think it would totally be within the scope of this project, we don't want people running out of GIFs 😂

It would be great if you could open a PR and we can see how we could include something like this in the extension 😃

**Comment by LeonardsonCC** [comment]
Opened #60
