### ISSUE TITLE
GIF Button missing on release new/edit page

### ISSUE THREAD

**Issue by pglombardo** [N1ck/gifs-for-github#65]
With the version `23.10.31`, the GIF button is missing in the release new/edit page.

Here is a screenshot of two browser windows, release edit on the left and comment box on the right.

<img width="1463" alt="Screenshot 2023-11-02 at 12 12 49" src="https://github.com/N1ck/gifs-for-github/assets/395132/0378ace2-e9e1-4333-843c-e29b50b155f5">

I blame Github who shouldn't ever change _anything_ in the UI.  :-)

Great extension BTW.  You [can see](https://github.com/pglombardo/PasswordPusher/releases) how long I've used it for with every release.

**Comment by N1ck** [comment]
Thanks for reporting. I will take a look at this today 😄 

Glad you like the extension!

<img src="https://media0.giphy.com/media/QXa8B7XoIXhF9WEafM/giphy.gif"/>
