### ISSUE TITLE
Double <img> insertion on GitHub Enterprise

### ISSUE THREAD

**Issue by clausjoergensen** [N1ck/gifs-for-github#67]
It inserts the `<img>` tag twice on GitHub Enterprise :(

No issue on github.com

Version: 23.11.6

**Comment by N1ck** [comment]
Thanks for reporting! This is a tough one as I don't have access to GitHub Enterprise 😅 

Just to confirm a couple of things:
1. Is it inserting the same string twice? e.g. `<img src="https://media1.giphy.com/media/mu8hBrHtPh0WEVPhCh/giphy.gif"/><img src="https://media1.giphy.com/media/mu8hBrHtPh0WEVPhCh/giphy.gif"/>`

2. GitHub recently updated their comment box, do you have this UI in enterprise? e.g.
<img src="https://user-images.githubusercontent.com/3369400/279429350-8f437511-ca20-46da-aa02-1270a22cd20a.png" />

3. You only have one version of the extension installed (check in chrome://extensions)? In the past I have seen this bug occur if you have the version on the [Chrome Webstore](https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep/related) as well as the extension locally 
![image](https://github.com/N1ck/gifs-for-github/assets/1018141/91abb83a-80cc-4814-b8d3-c2221bf1174b)

**Comment by clausjoergensen** [comment]
Interestingly, since reporting this and then re-checking today it have stopped doing the double inserts. I did install a updated version of Edge in the mean time, so perhaps that was the culprit.

1. Yes, this is exactly what happend
2. No, I only have one version installed
3. Yep, this is the enterprise UI

![](https://github.com/N1ck/gifs-for-github/assets/233721/acaad764-33e4-4620-8b65-c9919ed76878)

But since this now no longer reproduces, I'll close the ticket again.

Thanks for a great and fun browser extension :-)

**Comment by N1ck** [comment]
Thank you for following up. Please let me know if you have any issues with the extension going forward.

<img src="https://media0.giphy.com/media/M9NbzZjAcxq9jS9LZJ/giphy.gif"/>
