### ISSUE TITLE
No longer available for Firefox?

### ISSUE THREAD

**Issue by pcvandamcb** [N1ck/gifs-for-github#7]
The link to the Firefox extensions seems to be dead:
https://addons.mozilla.org/en-CA/firefox/addon/gifs-for-github/

**Comment by N1ck** [comment]
Sorry about that, the reviewer at Firefox has issues building the source code for the extension and I didn't get back to them in time (I was on holiday 😅) so they disabled it. 

I have re-submitted a version that should work, if it's not available now it should be very shortly!

**Comment by pcvandamcb** [comment]
![](https://media3.giphy.com/media/d2Z9QYzA2aidiWn6/giphy.gif)
