### ISSUE TITLE
GIF button appears below toolbar and makes toolbar unclickable

### ISSUE THREAD

**Issue by alexjurkiewicz** [N1ck/gifs-for-github#72]
Problem encountered with version **24.1.16** (latest at time of issue).

## Problem

<img width="943" alt="Screenshot 2024-01-18 at 10 14 29 am" src="https://github.com/N1ck/gifs-for-github/assets/379509/a63f0822-bfbe-4ed7-8895-d6bb540cde76">

(this image inspector shows elements in the toolbar, and then the final `<details>` element is what this addon inserts (I assume). The content extends over the entire toolbar.)

The GIF button renders below the toolbar and makes the rest of the toolbar unclickable. I can click the GIF button, but only in the upper parts which don't intersect the text box.

Looking at inspector in the above image, it seems like the `<details>` element is growing to cover the entire toolbar area.

## Potential Fix

Adding `float: left;` to the `<details>` style fixes the issue. This matches styling applied to all the `<div class="ActionBar-item">`
 elements.

A better fix might be to stick the `<details>` element into its own `<div class="ActionBar-item">`. I tested this in console and it seemed to work (I moved the item to first in the toolbar to show more inspector hierarchy).

<img width="1026" alt="Screenshot 2024-01-18 at 10 18 46 am" src="https://github.com/N1ck/gifs-for-github/assets/379509/23e10eb3-210d-4fb8-bd5d-b03baf0a3938">

Thank you for a great extension!

<img src="https://media3.giphy.com/media/wsA3PnuSThDFwL48jE/giphy.gif"/>

**Comment by N1ck** [comment]
Hey @alexjurkiewicz thank you for reporting the issue and for investigating!

I was actually using the extension when it broke and immediately submitted an update to the extension. Unfortunately it can take some time for them to review the extension before it goes live. 

The version with this fix is `24.1.18`. Hoping it gets approved soon.

<img src="https://media1.giphy.com/media/O6Hw3wYDqzUis/giphy.gif"/>

**Comment by N1ck** [comment]
I think that was about the longest it's taken for the extension to be reviewed, but it is now live. If you have version `24.1.18` this issue should be resolved.
