### ISSUE TITLE
Question: Does it work with Github Enterprise?

### ISSUE THREAD

**Issue by frankpeleato** [N1ck/gifs-for-github#77]
Title says it all. Our organization was migrated to Github Enterprise and the extension stopped working. Do you offer support for Github Enterprise?

<img src="https://media1.giphy.com/media/l4JyX3V0yydvPHNBe/giphy.gif"/>

**Comment by N1ck** [comment]
Hey @frankpeleato the extension should support GitHub Enterprise. To get it to work, while you are on the enterprise page, right click the extension and "Enable GIFs for GitHub on this Domain". Please let me know how you go!

![image](https://github.com/N1ck/gifs-for-github/assets/1018141/bcef18b6-ee3d-4679-9abd-e9c8edcba6bc)

**Comment by frankpeleato** [comment]
@N1ck Thank you!
![image](https://github.com/N1ck/gifs-for-github/assets/61477401/ba3b05f0-19eb-4aec-8c23-c0b731b7035a)
